lr: 0.0001
seed: 1
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 64
val_batch: 16
test_batch: 16
num_workers: 0
model_name: 'refine-64'
data_filepath: './data/'
dataset: 'ndvi1'
lr_schedule: [15, 30, 100, 300]
num_gpus: 1
epochs: 3000